baseURL = "https://jeromedesseaux.fr"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Jérôme Desseaux"
theme = "KeepIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = ""

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/articles/:filename/"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/articles/"
    weight = 1

  [[menu.main]]
    name = "Catégories"
    url = "/categories/"
    weight = 3

  [[menu.main]]
    name = "À propos"
    url = "/a-propos"
    weight = 4

[params]
    since = 2018
    author = "Jérôme Desseaux"               # Author's name
    subtitle = "Data Scientist et Développeur Fullstack freelance"       # Subtitle
    subsubtitle = "Python, Node.js, Vue"
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
    bing_verification = ""
    yandex_verification = ""
    pinterest_verification = ""
    baidu_verification = ""
    
    avatar = "/chest.jpg" #comment it to use gravatar
    socialShare = true
    
    description = "Ingénieur et développeur indépendant à Rouen : Réalisations sur-mesure, architecture, refonte et optimisations diverses; Rendons votre site attractif !" # site description
    keywords = "Développement Symfony PHP Rouen freelance indépendant Jérôme Desseaux Laravel web" # site keywords

    license= 'Released under <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.gravatar]
    #email = "example@gmail.com"   #uncomment and insert your email address to use gravatar


[params.social]
    GitHub = "JeromeDesseaux"
    Linkedin = "jeromedesseaux"
    Twitter = "jerome_desseaux"
    #Instagram = "xxxx"
    #Email   = "xxxx"
    #Facebook = "xxxx"
    #Telegram = "xxxx"
    #Medium = "xxxx"
    #Gitlab = "xxxx"
    #Youtubelegacy = "xxxx"
    #Youtubecustom = "xxxx"
    #Youtubechannel = "xxxx"
    #Tumblr ="xxxx"
    #Quora = "xxxx"
    #Keybase = "xxxx"
    #Pinterest = "xxxx"
    #Reddit = "xxxx"
    #Codepen = "xxxx"
    #Bitbucket = "xxxx"
    #Stackoverflow = "xxxxx"
    #Weibo = "xxxx"
    #Odnoklassniki = "xxxx"
    #VKontakte = "xxxx"
    #Flickr = "xxxx"
    #Xing = "xxxx"
    #Snapchat = "xxxx"
    #Soundcloud = "xxxx"
    #Spotify = "xxxx"
    #Bandcamp = "xxxx"
    #Paypal = "xxxx"
    #Fivehundredpx = "xxxx"
    #Mix = "xxxx"
    #Goodreads = "xxxx"
    #Lastfm = "xxxx"
    #Foursquare = "xxxx"
    #Hackernews = "xxxx"
    #Kickstarter = "xxxx"
    #Patreon = "xxxx"
    #Steam = "xxxx"
    #Twitch = "xxxx"
    #Strava = "xxxx"
    #Skype = "xxxx"
    #Whatsapp = "xxxx"
    #Zhihu = "xxxx"
    #Douban = "xxxx"
    #Angellist = "xxxx"
    #Slidershare = "xxxx"
    #Jsfiddle = "xxxx"
    #Deviantart = "xxxx"
    #Behance = "xxxx"
    #Dribble = "xxxx"
    #Wordpress = "xxxx"
    #Vine = "xxxx"
    #Googlescholar = "xxxx"
    #Researchgate = "xxxx"
    #Mastodon = "xxxx"
    #Thingiverse = "xxxx"

[params.share]
Twitter = true
Facebook = true
#Reddit = true
Linkedin = true
#Pinterest = true
#HackerNews = true
#Mix = true
#Tumblr = true
#VKontakte = true
#Douban = true
#Weibo = true

# Used only for Seo schema 
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Jérôme Desseaux"

  [params.publisher]
    name = "Jérôme Desseaux"

    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]
    url = "logo.png"
    width = 127
    height = 40

  [params.image]
    url = "cover.png"
    width = 800
    height = 600

# [params.gitalk]
# owner = "JeromeDesseaux"       # Your GitHub ID       
# repo = ""        # The repo to store comments    
# clientId = ""    # Your client ID      
# clientSecret = "" # Your client secret

# [params.valine]
#   enable = false
#   appId = 'your appId'
#   appKey = 'your appKey'
#   notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
#   verify = false # Verification code
#   avatar = 'mm'
#   placeholder = 'your comments ...'
#   visitor = true

# [params.utterances]       # https://utteranc.es/
#     owner = ""              # Your GitHub ID
#     repo = ""               # The repo to store comments

# [params.gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
#     owner = ""              # Your GitHub ID
#     repo = ""               # The repo to store comments
#     clientId = ""           # Your client ID
#     clientSecret = ""       # Your client secret

